LSSTTD-854 Iteratively fit plane and remove outliers for flatness analysis
lsst-camera-dh/metrology-data-analysis pull request #8
Opened 2017-01-06 08:42 UTC by sethdigel

This modifies the flatness analysis to iteratively fit a plane to the scan data, removing outliers (>4 sigma deviation) at each iteration.  The RSA/RTM scan data from TS5 in particular typically have a few very large outliers (several hundreds of microns) plus a number of outliers at the tens of microns level.  Iteration unbiases the effects of the outliers on the fit of the plane.  After the iterative fitting, the PV100 (full residual range) and PV95 values (range between 0.025 and 0.975 quantiles) are derived from residuals filtered at the 5 sigma level, relaxing the filtering of outliers somewhat relative to the plane fits, because the distribution of residuals typically has tails longer than Gaussian.  There's nothing particularly magic about 5 sigma but for an automated analysis it is safer than using an absolute threshold.  

The quantile table reported by the analysis remains as before, i.e., based on the residuals without filtering the outliers.  The histogram of residuals now shows only the +/-5 sigma range, and overlays a Gaussian with dispersion defined by the variance of the residuals for reference.

2017-03-13 22:49 UTC, jchiang87 requested changes

2017-03-13 22:49 UTC, jchiang87 commented on python/MetrologyData.py
> +        while stdev_new <> stdev_last:
I already noted that this should use `!=` instead of `<>` in the PR for LSSTTD-859

2017-03-13 23:31 UTC, sethdigel commented on python/MetrologyData.py
> +        while stdev_new <> stdev_last:
Thank you, Jim.  I've made this change.

2017-03-13 23:46 UTC, jchiang87 approved these changes

2017-03-13 23:52 UTC, merged

2017-03-14 23:12 UTC, jchiang87 commented on python/MetrologyData.py
> +        for ccd in range(0, 9):
I should have scrutinized these changes more carefully in the initial review.   This code needs to be used for single sensor metrology.  That fact that it is looping over `ccd`s (apparently in a raft) is a clear indication that these changes won't work in SR-MET-05, for example.  We're going to have to back out these changes.

2017-03-14 23:13 UTC, jchiang87 reviewed
Some of these changes won't work for single sensor metrology.